### ISSUE TITLE
Секреты Docker-а

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateSwarm#1]
https://github.com/NorthGateVologda/NorthGateSwarm/blob/f853f104b7e512a530b167d0b7249458cfbf20f5/postgres/docker-compose.yml#L9

Тут такая тема... Когда клонируешь Swarm репозиторий, меняешь отслеживаемые Git-ом файлы, а потом делаешь git pull может быть конфликт. Файлы не должны меняться в ручную на сервере. Пользователя в общем то можно прописать через переменную среды, а пароль через Docker Secretб можно оба передать через файл секрета, можно через файл секрета передать возможнео какой то PKI файл если у PG есть такая функция авторизации, но в общем то пользователя можно и захардкодить.

https://docs.docker.com/engine/swarm/secrets/

Я предлагаю вести `compose` в стиле *немодифицируемых* на хосте.

**Comment by sshiae** [comment]
Да, Оля, ты права! Так хардкодить никак нельзя. Согласен на счёт `Docker secrets`, что их лучше использовать.
Я реализовал `bash скрипт`, который будет читать все `docker secrets` из файла `.env` в главной директории и добавлять их в `Docker`. Далее в каждой директории будет тоже свой `bash скрипт`, который будет заниматься непосредственно деплоем `deploy.sh`, в нем будут прописаны все необходимые инструкции для успешного развертывания стэка в `Docker swarm`.

Файл `secrets.sh`, который читает секреты выглядит так:
![image](https://github.com/NorthGateVologda/NorthGateSwarm/assets/72744219/878654c0-8d1b-4396-9b3f-3a8caa603af3)

Файл `deploy.sh` для `postgres` выглядит следующим образом:
![image](https://github.com/NorthGateVologda/NorthGateSwarm/assets/72744219/68ba27de-5951-4f91-888c-f2e841ed4b05)

Такой `deploy.sh` будет для каждой директории

**Comment by sshiae** [comment]
Pull Request отправил с изменениями

**Comment by sshiae** [comment]
Секреты докера ввёл, теперь они будут везде использоваться, скажем нет хардкодингу)

**Comment by olgapshen** [comment]
> Секреты докера ввёл, теперь они будут везде использоваться, скажем нет хардкодингу)

Воистину!!!
