### ISSUE TITLE
Ссылки в Markdown-е

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateSwarm#2]
https://github.com/NorthGateVologda/NorthGateSwarm/blob/f853f104b7e512a530b167d0b7249458cfbf20f5/README.md?plain=1#L6

Мне кажется лучше сделать с сылками:

```md
- [postgres](postgrs/) *описание*
```

**Comment by sshiae** [comment]
Да, тоже так считаю, что лучше будет, в Pull Request добавил изменения

**Comment by sshiae** [comment]
Ссылочки поменял

**Comment by olgapshen** [comment]
> Ссылочки поменял

Супер!!!
