### ISSUE TITLE
Убрать CORS

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateSwarm#25]
https://github.com/NorthGateVologda/NorthGateSwarm/blob/7560387ba9e503d5a735841fbc02edb973f23206/backend/backend.env#L1

Учитывая что мы настроили доменные имена, мы можем проименовать хосты этими доменными именами и собственно говоря
безопасно убрать `CORS`. Хосты именуются настройкой `hostname` в `compose` файле.

**Comment by olgapshen** [comment]
@sshiae какая у нас будет финальная архитектура?

**Comment by sshiae** [comment]
Пока что CORS не планирую убирать, в будущем

**Comment by olgapshen** [comment]
Тогда закрываем.
